"""
    ispangram(input)

Return `true` if `input` contains every alphabetic character (case insensitive).

"""
function ispangram(input)
    alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
        "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

    # could replace with alphabet = 'a':'z'

    input = lowercase(input)

    # could have also have used unicode, e.g., subset or eq can be 
    # generated by typing \subseteq and then pressing tab for autocomplete

    pangramFlag = true
    for letter in alphabet
        if !occursin(letter, input)
            pangramFlag = false
        end
    end

    return pangramFlag

end